[package]
name = "utils_candle"
version = "0.1.0"
edition = "2021"

[dependencies]
local_utils = { path = "../../local_utils" }
candle-core = { version = "0.7.2", features = ["metal"] }
thiserror = "1.0.64"
