[package]
name = "kits"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.64"
tch = { version = "0.17.0", optional = true }
candle-core = { version = "0.7.2", features = ["metal"], optional = true }

[features]
default = []
tch = ["dep:tch"]
candle = ["dep:candle-core"]
