[package]
name = "blitz-beginner_source-candle"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { version = "0.7.2", features = ["metal"] }
kits = { path = "../../../kits", features=["candle"]}
